import * as readline from 'readline'
import * as fs from 'fs'
import * as path from 'path'
import * as crypto from 'crypto'

// ── Pure helpers (exported for testing) ──────────────────────────────────────

export function isValidGoogleClientId(id: string): boolean {
  return id.endsWith('.apps.googleusercontent.com') && id.length > '.apps.googleusercontent.com'.length
}

export function isValidAzureClientId(id: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)
}

export function isValidSecret(secret: string): boolean {
  return secret.trim().length > 0
}

export interface EnvOptions {
  encryptionKey: string
  googleClientId: string
  googleClientSecret: string
  microsoftClientId: string
  microsoftClientSecret: string
}

export function buildEnvContent(opts: EnvOptions): string {
  return [
    '# InboxMY Configuration — generated by npm run setup',
    '',
    '# Server',
    'PORT=3001',
    'DATA_DIR=./data',
    '',
    '# Encryption (auto-generated — do not change or you cannot decrypt your data)',
    `ENCRYPTION_KEY=${opts.encryptionKey}`,
    '',
    '# Google OAuth (Gmail)',
    `GOOGLE_CLIENT_ID=${opts.googleClientId}`,
    `GOOGLE_CLIENT_SECRET=${opts.googleClientSecret}`,
    'GOOGLE_REDIRECT_URI=http://localhost:3001/auth/gmail/callback',
    '',
    '# Microsoft OAuth (Outlook)',
    `MICROSOFT_CLIENT_ID=${opts.microsoftClientId}`,
    `MICROSOFT_CLIENT_SECRET=${opts.microsoftClientSecret}`,
    'MICROSOFT_REDIRECT_URI=http://localhost:3001/auth/outlook/callback',
    '',
    '# Sync interval in minutes (default: 15)',
    'SYNC_INTERVAL_MINUTES=15',
    '',
  ].join('\n')
}

// ── Wizard (only runs when invoked directly) ─────────────────────────────────

async function main(): Promise<void> {
  // Implemented in Task 5
}

if (require.main === module) {
  main().catch((err) => {
    console.error('Setup failed:', err.message)
    process.exit(1)
  })
}
